### ISSUE TITLE
Recognized mutated values as changed

### ISSUE THREAD

**Issue by Haniyya** [Stex/setting_accessors#12]
## Scenario:

When having some setting with a default value of `{}` or `[]` or some such, mutations to that value do not constitute a `#changed?` true and will thus not be saved in rails 5.

So if I have a 
```rb
        setting_accessor :james_settings, :type => :polymorphic, :default => {}
```
And I have special methods like
```rb
def drinks_milk=(does_he)
  james_setting[:drinks_milk] = does_he
end
```
Then calls like 
```rb
stuff.update_attribute(:drinks_milk, true)
```
Will not cause `stuff` to be persisted.

Same same but different with arrays and `push` stuff I'd guess.

**Comment by Stex** [comment]
There is actually a [spec covering exactly this case](https://github.com/Stex/setting_accessors/blob/master/spec/lib/setting_accessors/integration_spec.rb#L108)... so either the spec is not sufficient or it's a different problem.

I created a small example which passes:

```ruby
describe 'james_problem' do
  with_model 'James' do
    model do
      setting_accessor :james_settings, :type => :polymorphic, :default => {}

      def drinks_milk=(does_he)
        james_settings[:drinks_milk] = does_he
      end
    end
  end

  it 'updates the current milk drinking status with update_attribute' do
    james = James.create
    expect(james.james_settings[:drinks_milk]).to be nil
    james.update_attribute(:drinks_milk, true)
    expect(James.find(james.id).james_settings).to include(drinks_milk: true)
  end
end
```

@Haniyya Could you take a look at my example? Maybe I have an error in reasoning here.

**Comment by Stex** [comment]
Found the problem(s):

1. `#value_was` could override the temp settings through `#get` under certain circumstances

When a setting already exists in the database and is only written without reading it first, it will not yet be part of the temp settings. 

This means that the fallback in `#value_was` would call `#get` which would then load the current value from the database **and save it in the temp settings again**, overriding the user-set value.

2. `SettingSet#persist!` persists everything in the temp settings, not only actually changed ones

This is a problem because we have to add default values to the temp settings to make them mutable, otherwise, changes would simply be lost:

```ruby
setting_accessor :my_hash, type: :polymorphic, default: {}

r = new
# => If the default value ({}) would not be written to the temp settings, the following line would never end up in there
r.my_hash[:something] = true
```

3. `#value_changed?` does not check for default values

As described in 2., default values have to be copied to the temp settings. As `#value_changed?` operates on said temp settings to determine whether the new and old values differ, we have to make sure that it doesn't count the default values as user-made changes.

**Comment by Stex** [comment]
While working on this, I discovered another interesting bug which needs a quite specific setup:

```ruby
describe 'james_other_problem' do
  with_model 'James' do
    model do
      setting_accessor :favourite_things, default: []
    end
  end

  it 'handles mutating and normal set actions correctly' do
    james = James.create
    james.favourite_things << 'milk'
    james.save

    james.reload

    james.favourite_things << 'tea'
    james.favourite_things = james.favourite_things.take(10) # one can only like so many things
    james.save

    expect(James.find(james.id).favourite_things).to match_array ['milk', 'tea']
  end
end

# expected collection contained:  ["milk", "tea"]
# actual collection contained:    ["milk"]
# the missing elements were:      ["tea"]
```

The prerequisites are:

1. The setting has to exist in the database
2. The setting has to be mutated without reading it first
3. The setting has to be set using `#set` afterwards

This causes `SettingSet#track_old_value` to take the mutated value instead of the one in the database.
